const defaultValue = [
  "ANGEL HIGH",
  "Attivio",
  "BAUER",
  "BAZUMI",
  "BabyGo",
  "Babyton",
  "Barbie",
  "CRY BABIES",
  "Cosmodrome Games",
  "Demi Star",
  "Enchantimals",
  "Fisher Price",
  "FurReal Friends",
  "GooJitZu",
  "Harry Potter",
  "Hasbro Games",
  "Hot Wheels",
  "Im.Master",
  "Infinity Nado",
  "Jurassic World",
  "Kiddieland",
  "L.O.L. Surprise!",
  "LEGO",
  "Laffi",
  "Mobicaro",
  "Monopoly",
  "My Little Pony",
  "Nerf",
  "Ocie",
  "PAREMO",
  "PELICAN HAPPY TOYS",
  "Paw Patrol",
  "Pets Alive",
  "Rainbocorns",
  "Rastar",
  "Silverlit",
  "Star Wars",
  "Thomas &Friends",
  "Tiny Love",
  "X-SHOT",
  "YCOO",
  "Zapf Creation",
  "Zeimas",
  "alilo",
  "Полесье",
  "ТОБОТ",
  "УМка",
];
export default defaultValue;
